"""
Test Gap Agent — STUB (Member 3 owns the real implementation).

This stub satisfies the function signature agreed with Member 2 so that
orchestrator.py can call it without modification when Member 3 swaps in the
real implementation.
"""
from __future__ import annotations
import logging
import os
import re

from orchestrator.schemas import ImpactedRule, TestGap

logger = logging.getLogger(__name__)


def analyze(diff: str, impacted_rules: list[ImpactedRule], repo_path: str) -> list[TestGap]:
    """
    Check test coverage for each impacted rule and, if missing, generate a
    regression test.

    Args:
        diff:            Raw unified-diff string of the PR.
        impacted_rules:  Output of the Change Impact Agent.
        repo_path:       Path to the repository under analysis.

    Returns:
        A list of TestGap — one per impacted rule.

    NOTE: This is a stub implementation. The real implementation (Member 3)
    will walk repo_path/tests/**, run coverage heuristics, and call the LLM
    to generate real Jest tests.
    """
    gaps: list[TestGap] = []

    for impacted in impacted_rules:
        has_coverage = _cheap_coverage_check(impacted, repo_path)

        if has_coverage:
            gaps.append(TestGap(
                rule_id=impacted.rule_id,
                has_coverage=True,
                generated_test_path=None,
                generated_test_code=None,
            ))
        else:
            # Generate a minimal stub test so the pipeline has something to show
            test_code = _generate_stub_test(impacted, diff)
            test_path = f"{repo_path}/tests/generated/rule_{impacted.rule_id.lower().replace('-', '_')}_regression.test.js"

            # Write it to disk if possible
            _write_test_file(test_path, test_code)

            gaps.append(TestGap(
                rule_id=impacted.rule_id,
                has_coverage=False,
                generated_test_path=test_path,
                generated_test_code=test_code,
            ))

    return gaps


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _cheap_coverage_check(impacted: ImpactedRule, repo_path: str) -> bool:
    """
    Heuristic: scan test files for references to any function in the call chain.
    Returns True only if we find a test that BOTH calls a relevant function AND
    asserts on the outcome of a 'CANCELLED' path.
    """
    tests_dir = os.path.join(repo_path, "tests")
    if not os.path.isdir(tests_dir):
        return False

    chain_lower = [fn.lower() for fn in impacted.affected_call_chain]

    for dirpath, _, filenames in os.walk(tests_dir):
        for fname in filenames:
            if not (fname.endswith(".test.js") or fname.endswith(".spec.js") or fname.endswith(".test.ts")):
                continue
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, encoding="utf-8") as f:
                    content = f.read().lower()
                if any(fn in content for fn in chain_lower) and "cancelled" in content:
                    return True
            except OSError:
                continue

    return False


def _generate_stub_test(impacted: ImpactedRule, diff: str) -> str:
    """
    Generate a minimal Jest test stub that demonstrates the violation scenario.
    Member 3's real implementation replaces this with LLM-generated code.
    """
    rule_id = impacted.rule_id
    call_chain = impacted.affected_call_chain or ["<unknown>"]
    entry_fn = call_chain[0] if call_chain else "unknownFunction"
    final_fn = call_chain[-1] if call_chain else "unknownFunction"

    return f"""\
/**
 * Regression test for {rule_id}
 * Auto-generated by InvariantOS Test Gap Agent (stub).
 * Rule: {impacted.reason}
 *
 * This test MUST FAIL on the buggy branch and PASS on the fixed branch.
 * Replace the stub body with real assertions once Member 3's agent is live.
 */

const {{ {entry_fn} }} = require('../../src/orders');
const {{ shipmentJob }} = require('../../src/shipments');
const warehouseApi = require('../../src/warehouseApi');

jest.mock('../../src/warehouseApi');

describe('{rule_id} regression', () => {{
  beforeEach(() => {{
    jest.clearAllMocks();
  }});

  test('A CANCELLED order must NOT trigger createShipment', async () => {{
    const order = {{ id: 'test-order-1', status: 'CANCELLED' }};

    await shipmentJob(order);

    // This assertion should FAIL on the buggy branch (status !== 'CANCELLED' lets it through)
    // and PASS on the fixed branch (status === 'PAID' guard blocks it)
    expect(warehouseApi.createShipment).not.toHaveBeenCalled();
  }});

  test('A PAID order SHOULD trigger createShipment', async () => {{
    const order = {{ id: 'test-order-2', status: 'PAID' }};

    await shipmentJob(order);

    expect(warehouseApi.createShipment).toHaveBeenCalledWith(order);
  }});
}});
"""


def _write_test_file(path: str, code: str) -> None:
    """Write generated test to disk if the directory exists."""
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
        logger.info("Generated test written to %s", path)
    except OSError as exc:
        logger.warning("Could not write generated test to %s: %s", path, exc)
